name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build image
      run: docker build -t compilerexplorer/windows:latest .
    - name: Push to Docker Hub
      run: docker image push compilerexplorer/windows:latest
